spring:
  application:
    name: twm-rendering-service

server:
  port: ${EUREKA_REGISTRATION_PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:2012/eureka}
  instance:
    preferIpAddress: true